### ISSUE TITLE
Status and plan before fork

### ISSUE THREAD

**Issue by kke** [k8s-ruby/k8s-ruby#1]
The latest version was 0.10.4. A couple of 0.10 releases were made from the `v0.10` branch because the `master` branch was on it's way to become version 1.0 but there were bugs that had to be fixed asap.

My original plans to get squeezed in before 1.0 were:

- Slice it up a little by extracting independent modules into their own gems
- Refactor how instances are created, because currently it's quite an amoeba. The original issue with my thoughts on how it perhaps should look like: https://github.com/kontena/k8s-client/issues/121
- Minimize dependencies: dry dependencies caused a lot of problems with projects that were using dry gems on their own, but those were already dropped in the master. I would also consider getting rid of RecursiveOpenStruct (because it's a bit silly) and Excon (because an API client gem should not bring in yet another HTTP client library. If you connect to a couple of API's, your project will suddenly include Faraday, HTTPParty, Excon and a couple of others and their child dependencies and grand child dependencies) There's also still a dependency to the `yaml-safe_load_stream` that is under Kontena: https://github.com/kontena/yaml-safe_load_stream). The yajl-ruby (includes native extensions) was made optional in `master` I think (I recall it can now also use OJ which is faster?)
- Include a `CHANGELOG` . 
- Create a set of simple example programs into `example/`. The original `bin/k8s-client` served that purpose for a while but got outdated.
- Add exceptionless variants of the api query methods, because as it is now, you constantly need to `rescue`. Instead of being simply able to do something like `client.api('v1').resource('configmaps').get('cluster-info')&.metadata&.uid` you have to `rescue K8s::NotFound`. I already implemented this in https://github.com/kontena/k8s-client/pull/119 but ended up closing it without merging because I thought the implementation was too complex (I think it was difficult to keep in sync with the other refactorings going on at the time).

Known bugs:
- KubeConfig loading should track the path of each loaded file: https://github.com/kontena/k8s-client/issues/167 (I'd rather see a separate `k8s-kubeconfig` gem taking care of this.
- Some threat detection systems get triggered by the authentic looking client certificate in the spec suite, should probably replace that with something less suspicious.

**Comment by pre** [comment]
Previous `master` branch has been renamed `dev` as it seemed unstable for use. 
Once `dev` stabilises, it could be merged into `master` and `v1.0` released from it. 

Latest v0.10.15 was made from `v0.10` branch. 

As of now, k8s-ruby's `master` branch is the stable branch.

**Comment by kke** [comment]
This issue can be closed as it is mostly just informational.

**Comment by pre** [comment]
Would be nice to get the `dev`branch stabilised (ie removing dependencies to `dry-struct` and `dry-types`) and merging in updated version of RecursiveOpenStruct for Ruby 2.7.0 compatibility https://github.com/k8s-ruby/k8s-ruby/issues/2 .

**Comment by pre** [comment]
I created issues of their own for all the bullet points except this: 
* "Some threat detection systems get triggered by the authentic looking client certificate in the spec suite, should probably replace that with something less suspicious." 

Fixing this would need more information, please create an issue if you have a problem report or further details.
