### ISSUE TITLE
Fork not insync?

### ISSUE THREAD

**Issue by danquack** [k8s-ruby/k8s-ruby#13]
@kke 
So I was having conflicts with drytypes, which prompted me to open #12, however it appears the  master removed drytypes all together:
https://github.com/kontena/k8s-client/pull/147/files

Is this fork still active in sync?

**Comment by danquack** [comment]
Relates to #4

**Comment by pre** [comment]
> Is this fork still active in sync?

Think about it the other way: Kontena Inc. as a company is dead, which means that anything in github.com/kontena is no longer maintained. No one can either update any code in github.com/kontena.

The `master` branch of kontena/k8s-client is the `dev` branch in k8s-ruby. The work of removing dry-types was not completed in the kontena/k8s-client repository, hence, `master` of k8s-ruby points to the commit where the last gem version was published.

The PR #12 looks very simple but I need to at least run the unit tests on my own and test in my own project whether it causes any issues downstream. The k8s-ruby does not currently have any CI configured to automatically run any tests. 

I'm in the process of migrating my projects to https://github.com/kubernetes/client-go 

The ecosystem of Kubernetes is in the Go land - the effort going in the Go libraries is so huge that writing meaningful software with home baked Kubernetes libraries in any other language just does not pay the effort in the long run.

**Comment by danquack** [comment]
Thanks for the clarification! Actually didn’t think to check the dev branch, this can be closed!
