### ISSUE TITLE
Ruby 2.7.0 support

### ISSUE THREAD

**Issue by pre** [k8s-ruby/k8s-ruby#2]
Tests fail on Ruby 2.7.0.

Related issue in RecursiveOpenStruct library: https://github.com/aetherknight/recursive-open-struct/issues/62

**Comment by kke** [comment]
I suppose this will self-fix once they close https://github.com/aetherknight/recursive-open-struct/pull/64 and make a new release.

**Comment by jakolehm** [comment]
Version `1.1.1` seems to include the fix.

**Comment by matti** [comment]
2.7 works with master, 3.x does not
