### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by notjames** [k8s-ruby/k8s-ruby#20]
Is it dead? Anyone maintaining it? Anyone going to maintain it if it's not currently being maintained? KTHXBYE

**Comment by matti** [comment]
I'm using this in production. sofar it works.

**Comment by pre** [comment]
it works , don't touch it :D 

For future development, the Go kubernetes client library is the way to go. Also operator-sdk and kubebuilder are nowdays the same project on the client side. 

There's not really much point having a custom Ruby k8s library, it'll always be at least partially broken.

**Comment by notjames** [comment]
problem is, I don't like developing in Golang if I don't have to. Sooo...yeah.

**Comment by matti** [comment]
maybe you could `system("kubectl apply -f ...")`

anyway,
- this gem works and because how it is built it should continue working
- only golang k8s library will be updated as k8s goes forward

**Comment by notjames** [comment]
> maybe you could `system("kubectl apply -f ...")` anyway, - this gem works and because how it is built it should continue working - only golang k8s library will be updated as k8s goes forward
> […](#)
> On 16. Apr 2021, at 4.43, Jim Conner ***@***.***> wrote: ﻿ problem is, I don't like developing in Golang if I don't have to. Sooo...yeah. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

system() calls imo are no bueno. Nevertheless, good to know that it's built fairly sturdy. Sad, imo, that only one library will continue to be developed in the future. OH well.
