### ISSUE TITLE
Ruby 3.1 support

### ISSUE THREAD

**Issue by MiguelSavignano** [k8s-ruby/k8s-ruby#25]
Can't install `k8s-ruby` gem using Ruby 3.1 with bundler

Error:
```
Bundler found conflicting requirements for the Ruby version:
  In Gemfile:
    Ruby (~> 3.1)

    k8s-ruby was resolved to 0.10.5, which depends on
      Ruby (~> 2.4)

Ruby (~> 2.4), which is required by gem 'k8s-ruby', is not available in the local ruby installation
```

**Comment by matti** [comment]
https://github.com/k8s-ruby/k8s-ruby/blob/master/k8s-ruby.gemspec

I think that just updating this would be the first step.

There are almost no people working on this gem, so if you could make a PR?

**Comment by matti** [comment]
I tried to do this, dry-types/struct is the problem. Don't have time to figure out.

**Comment by matti** [comment]
somebody needs to fix this: https://github.com/k8s-ruby/k8s-ruby/pull/29
