### ISSUE TITLE
MAINTAINERS NEEDED

### ISSUE THREAD

**Issue by matti** [k8s-ruby/k8s-ruby#27]
for example #29

**Comment by matti** [comment]
update: ruby 3.0 is now supported, 3.1 is not - still looking for maintainers

**Comment by tadman** [comment]
Is there a rough roadmap or place (Slack? Discord? IRC?) where this will (eventually?) be coordinated? I'd like to see better support for Ruby + Kubernetes, and if this is the new de-facto client I'd like to help, as that's important to what I'm working on.

**Comment by matti** [comment]
there used to be a slack, but its dead. the best bet now is this thread. 

imo discord is more accessible than slack (no need for invite bot)

want to setup something?

there is no road map - no real updates have been done for the last two years, but I am still using this in production.

**Comment by matti** [comment]
and to further clarify - this gem is well made so that it requires very little maintenance.

currently there is basically 0 maintainers - whoever wants to hop in, can do so.

**Comment by tadman** [comment]
I can do my best to chip in on priority issues. If there's a Discord channel let me know.

**Comment by r3cha** [comment]
@Matti I used this for production as well and can help with current task

**Comment by matti** [comment]
@r3cha cool just help with #29 and @tadman and everybody can do it too

I am no longer using this gem in production - refactored all code to either just exec kubectl or use golang.

So I am more than happy to give 100% ownership of this repo/gem to whoever finalizes 3.1 support and 3.2 and so on

**Comment by DrBu7cher** [comment]
Hey, I think it should be community effort to upgrade the gem. The dependencies are currently not up to date and I would like to change that with a PR, as long as you tell me, this will get merged soon.
I think if you would give more people write access, we could get this gem maintained together. Maybe you only upload new "done" versions. Would this be a possibility for you?

**Comment by matti** [comment]
Sure, I can give maintainer access to whoever.

Having said that giving maintainer access to k8s-ruby wont immediately solve this as the dependency needs to be published first as a new gem with a new bame.

Please publish the dependency and then I'm convinced.

**Comment by DrBu7cher** [comment]
Why can't you give the currently public gem to someone new as well? Why does it have to be a new gem with a new name?

**Comment by DrBu7cher** [comment]
I feel it would be way easier to just give someone maintainer access to the repo and make them a [gem owner](https://guides.rubygems.org/command-reference/#gem-owner), so references to the existing gem don't break.
This would basically mean no effort for you in the future regarding this gem. Or am I mistaken? Please give more information about what the problem with the gem is?

**Comment by matti** [comment]
@DrBu7cher I am willing to give maintainer access to anybody willing and make them gem owners as well.

the problem I was referring above is that there is some dependency gem that is not under my control.

**Comment by matti** [comment]
So, somebody should fork @tsutsu's yaml-safe_load_stream2 and merge this PR https://github.com/tsutsu/yaml-safe_load_stream2/pull/1 by @dwillett and then update the dependencies of this gem to use the fork.

**Comment by matti** [comment]
^-- straightforward task for the next maintainer of this (and the forked yaml-safe_load_stream2) gem

**Comment by matti** [comment]
@Vasu1105 see above

**Comment by matti** [comment]
closing this issue as @Vasu1105 is taking over

**Comment by will-r** [comment]
@Vasu1105 how's this going? I would be happy to help.
